routes:
  - name: project#index
    url: /
    verb: GET

  - name: project#create
    url: /
    verb: POST

  - name: project#show
    url: /project/{id}
    verb: GET

  - name: project#update
    url: /project/{id}
    verb: POST

  - name: project#destroy
    url: /project/{id}/destroy
    verb: POST



  - name: detail#index
    url: /project/{id}/detail
    verb: GET

  - name: detail#create
    url: /project/{id}/detail
    verb: POST

  - name: detail#update
    url: /project/{id}/detail
    verb: POST

  - name: detail#destroy
    url: /project/{id}/detail/delete
    verb: POST



  - name: notes#index
    url: /project/{id}/notes
    verb: GET

  - name: notes#newNote
    url: /project/{id}/notes/new
    verb: GET

  - name: notes#create
    url: /project/{id}/notes
    verb: POST

  - name: notes#show
    url: /project/{id}/notes/{noteId}
    verb: GET

  - name: notes#update
    url: /project/{id}/notes/{noteId}
    verb: POST

  - name: notes#destroy
    url: /project/{id}/notes/{noteId}/delete
    verb: POST